name: 04-Using Actions

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    #the code below removes duplicate code
    defaults:
      run:
        working-directory: 04-using-actions/create-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v3 # supposed to run actions/setup-node@v3 and not actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
       # working-directory: 04-using-actions/create-app
      - name: Run Tests
        run: npm run test
      #  working-directory: 04-using-actions/create-app


#0. Check out code form repo because sometimes workflows don't have access to the code
#1. Install dependencies
#2. Run tests
#3. Build app
#4. Deploy app