name: 11- Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: "Skip deployment and only build output"

      target:
        type: environment
        required: true
        description: "Which environment will the workflow target"

      tag:
        type: choice
        options:
         - v1
         - v2
         - v3
        default: "v3"
        description: "Which version of the application to deploy"
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Build
          run: echo "Building project from tag ${{ inputs.tag}}"

    deploy:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ inputs.dry-run == false}}
      env:
        target: ${{ inputs.target}}
      steps:
        - name: Deploy
          run: echo "Deploying to ${{ inputs.target}}"
