name: 12 -1 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Build status"

      target:
        type: environment
        required: true
        description: "Which environment will the workflow target"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}
    steps:
      - name: Print GITHUB OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        run: |
         echo "$GITHUB_OUTPUT"
         echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
         echo "output1=value1" >> "$GITHUB_OUTPUT"
         echo "output2=value2" >> "$GITHUB_OUTPUT"
         cat "$GITHUB_OUTPUT"
        id: build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: |
         echo "Deploying to ${{ inputs.target }}"
         echo "Output 1: ${{ needs.build.outputs.output1 }}" 
         echo "Output 2: ${{ needs.build.outputs.output2 }}" 
         echo "Build Status: ${{ needs.build.outputs.build-status }}" 
