name: 15 - Working with Matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{matrix.os}} - ${{matrix.node-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18.x", "20.x", "22.x"]
        os: ["ubuntu-latest", "windows-latest"]
        include:
          - node-version: "18.x"
            os: "ubuntu-latest"
          - node-version: "22.x"
            tag: experimental
            os: "ubuntu-latest"
        exclude:
          - os: "windows-latest"


    steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


    - name: Fail if experimental
      if: matrix.tag == 'experimental'
      run: echo "Job is experimental"

    - name: Perform some Tests
      run: echo "Running tests on ${{ matrix.os }} with Node ${{ matrix.node-version }}"

    - name: Upload Test Results
      run: echo "Uploading test results to GitHub"

  include-example:
    name: ${{ matrix.color }} - ${{ matrix.size }} - ${{ matrix.shape }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        color: [red, green, blue]
        size: [small, large]
        shape: [circle, square]

        include:
        - color: yellow
          size: medium
          shape: triangle

    steps:
     - name: Print matrix
       run: echo "Color - ${{ matrix.color }} Size - ${{ matrix.size }} Shape - ${{ matrix.shape }}"


