name: 16 - Working with Environments
run-name: 16 - Working with Environments | env ${{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        required: true
        default: "prod"
        description: "Target environment to deploy to"

jobs:
   echo:
     runs-on: ubuntu-latest
     env:
       my_env_value : ${{ vars.MY_ENV_VALUE || 'default value' }}
     steps:
      - name: Echo vars
        run: |
          echo "Deploying to ${{ inputs.target-env }}"
          echo "Env variable: ${{ env.my_env_value }}"
