name: 17-1 Custom Actions - Composite
run-name: Custom Actions - Composite | env - ${{inputs.target-env}}
on:
  workflow_dispatch:
    inputs:
      target-env:
        required: false
        description: The target environment for the action
        type: choice
        options:
          - dev
          - prod
        default: dev
env:
  working-directory: 17-custom-actions/react-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '20.x'
          working-dir: ${{ env.working-directory }}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
