name: 17-2 - Custom Actions - JS
run-name: 17-2 - Custom Actions - JS
on:
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/actions/js-dependency-update
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update dependencies
        uses: ./.github/actions/js-dependency-update


