name: 17-2 - Custom Actions - JS
run-name: 17-2 - Custom Actions - JS | BB - ${{ inputs.base-branch }} - TB - ${{ inputs.target-branch }} - WD - ${{ inputs.working-directory }}
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: Base branch from which to check for updates
        default: main
        required: false
      target-branch:
        default: update-dependencies
        description: Branch to which the PR will be created
        required: false
      working-directory:
        description: Directory in which to run the action
        required: true
        default: 17-custom-actions/react-app
permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update dependencies
        id: update-deps
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print custom action output
        run: |
          echo "Updates available: ${{ steps.update-deps.outputs.updates-available }}"


