name: 17-3 - Custom Actions - Docker
run-name: 17-3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        default: 'https://www.google.com'
        required: false
        description: URL to ping
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping Url
        uses: ./.github/actions/docker-ping-url
        with:
         url: ${{ inputs.url }}



